version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  build-docker-image:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t my-node-app .
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
      - build-docker-image